/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.mykingdom.pdfreader;

import java.io.File;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiFileProxy;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiUIView;

import com.joanzapata.pdfview.PDFView;

import android.app.Activity;
import android.util.AttributeSet;
import android.util.Log;

// This proxy can be created by calling Pdfreader.createReader({message: "hello world"})
@Kroll.proxy(creatableInModule = PdfreaderModule.class)
public class ReaderProxy extends TiViewProxy {

	// Standard Debugging variables
	private static final String TAG = "ReaderProxy";

	private class ReaderView extends TiUIView {

		// Static Properties
		public static final String PROPERTY_FILE_PATH = "file";

		private PDFView pdfView;

		public ReaderView(TiViewProxy proxy) {
			super(proxy);
			TiCompositeLayout view = new TiCompositeLayout(proxy.getActivity());
			TiApplication appContext = TiApplication.getInstance();
			AttributeSet as = null;
			pdfView = new PDFView(appContext, as);
			view.addView(pdfView);
			setNativeView(view);
		}

		@Override
		public void processProperties(KrollDict d) {

			if (d.containsKey(PROPERTY_FILE_PATH)) {
				try {
					TiFileProxy fileProxy = (TiFileProxy) d
							.get(PROPERTY_FILE_PATH);
					File file = fileProxy.getBaseFile().getNativeFile();
					if (file.exists()) {
						pdfView.fromFile(file).load();
					}
				} catch (Exception ex) {
					String err = (ex.getMessage() == null) ? "Something wrong with the file given"
							: ex.getMessage();
					Log.e(TAG, err);
				}
			}

			super.processProperties(d);
		}

	}

	// Constructor
	public ReaderProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity activity) {
		TiUIView view = new ReaderView(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
	}

	// Methods
	@Kroll.method
	public void loadPDFFromFile(TiFileProxy file) {
		setPropertyAndFire(ReaderView.PROPERTY_FILE_PATH, file);
	}
}